/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rtrsc.view;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JToggleButton;
import lk.ijse.rtrsc.controller.ManageSheetController;
import lk.ijse.rtrsc.dto.SheetDto;

/**
 *
 * @author Gnanod-PC
 */
public class FirstClass extends javax.swing.JPanel {

    /**
     * Creates new form FirstClass
     */
    ReservationFrame reservationFrame=null;
    private ReservationFrame reservation = new ReservationFrame();
    public FirstClass() {
      
    }

    FirstClass(ReservationFrame aThis) {
          initComponents();
          this.reservation=aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
//    private void ShowFirstClass(List<SheetDto> sheetDto) {
//        if (sheetDto == null) {
//            return;
//        }
//
//        Component[] comp = FirstClass.getComponents();
//        JToggleButton[] btn = new JToggleButton[pnlFirstClass.getComponentCount()];
//        int i = 0;
//        for (Component component : comp) {
//            btn[i] = (JToggleButton) component;
//            i++;
//        }
//        int x = 0;
//        for (SheetDto dto : sheetDto) {
//            if (dto.getSheetType().equals("FirstClass")) {
//
//                try {
//                    btn[x].setText(dto.getSheetID() + "");
//
////                if(reservedSheets==null){
////                    return;
////                }
//                    Date date = jDateChooser.getDate();
//                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MMM-dd");
//                    String reserveDate = dateFormat.format(date);
//                    Object[] getAllr = {btn[x].getText(), reserveDate};
//                    int all = ManageSheetController.getCountAllCount(getAllr);
//                    if (all != 0) {
//                        btn[x].setBackground(Color.BLUE);
//                    }
//                    x++;
//                } catch (Exception ex) {
//                    Logger.getLogger(ReservationFrame.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        }
//    }

}
