/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rtrsc.view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.rmi.server.UnicastRemoteObject;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.rtrsc.controller.ManagePriceController;
import lk.ijse.rtrsc.controller.ManageSheetController;
import lk.ijse.rtrsc.controller.ManageUserController;
import lk.ijse.rtrsc.controller.ManageWagonController;
import lk.ijse.rtrsc.dto.SheetDto;
import lk.ijse.rtrsc.dto.UserDto;
import lk.ijse.rtrsc.dto.WagonDto;
import lk.ijse.rtrsc.observer.Observer;

/**
 *
 * @author Gnanod
 */
public class ManageSheets extends javax.swing.JPanel implements Observer {
    //  private User user;

    /**
     * Creates new form UserPanel
     */
    private DefaultTableModel dtm;
    private int sheetId;
    private String status;

    public ManageSheets() {
        initComponents();
        dtm = (DefaultTableModel) tblSheet.getModel();
        
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageSheetController.getSubject().registerObserver(this);
        } catch (Exception ex) {
            Logger.getLogger(ManageTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
        getAllSheets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbGenderGroup = new javax.swing.ButtonGroup();
        pnlManageUser = new javax.swing.JPanel();
        txtWagonId = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnObservation = new javax.swing.JRadioButton();
        btnThird = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        btnSecond = new javax.swing.JRadioButton();
        btnFist = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSheet = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1070, 660));

        pnlManageUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlManageUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWagonId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtWagonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWagonIdActionPerformed(evt);
            }
        });
        txtWagonId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWagonIdKeyPressed(evt);
            }
        });
        pnlManageUser.add(txtWagonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 400, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(27, 157, 175));
        jLabel16.setText("         WagonId");
        jLabel16.setToolTipText("");
        jLabel16.setOpaque(true);
        jLabel16.setRequestFocusEnabled(false);
        pnlManageUser.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 180, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(27, 157, 175));
        jLabel13.setText("        Sheet Type");
        jLabel13.setToolTipText("");
        jLabel13.setOpaque(true);
        jLabel13.setRequestFocusEnabled(false);
        pnlManageUser.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 170, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 126, 120));
        jLabel5.setText("                        Manage  Sheet");
        jLabel5.setToolTipText("");
        pnlManageUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 770, 50));

        btnObservation.setBackground(new java.awt.Color(255, 255, 255));
        cmbGenderGroup.add(btnObservation);
        btnObservation.setText("Observation Saloon");
        btnObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObservationActionPerformed(evt);
            }
        });
        pnlManageUser.add(btnObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 150, -1));

        btnThird.setBackground(new java.awt.Color(255, 255, 255));
        cmbGenderGroup.add(btnThird);
        btnThird.setText("ThirdClass");
        btnThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThirdActionPerformed(evt);
            }
        });
        pnlManageUser.add(btnThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 90, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlManageUser.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 130, 40));

        btnSecond.setBackground(new java.awt.Color(255, 255, 255));
        cmbGenderGroup.add(btnSecond);
        btnSecond.setText("SecondClass");
        btnSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondActionPerformed(evt);
            }
        });
        pnlManageUser.add(btnSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 90, -1));

        btnFist.setBackground(new java.awt.Color(255, 255, 255));
        cmbGenderGroup.add(btnFist);
        btnFist.setText("FirstClass");
        pnlManageUser.add(btnFist, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 90, -1));

        tblSheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select ", "SheetId", "WagonId", "SheetType", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSheet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSheetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSheet);
        if (tblSheet.getColumnModel().getColumnCount() > 0) {
            tblSheet.getColumnModel().getColumn(0).setMinWidth(50);
            tblSheet.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblSheet.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        pnlManageUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 427, 610, 190));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlManageUser.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 130, 40));

        jButton2.setText("Delete");
        pnlManageUser.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlManageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtWagonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWagonIdActionPerformed

    }//GEN-LAST:event_txtWagonIdActionPerformed

    private void txtWagonIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWagonIdKeyPressed


    }//GEN-LAST:event_txtWagonIdKeyPressed

    private void btnObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObservationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String wagonId = txtWagonId.getText();
            WagonDto wagon = new WagonDto();

            WagonDto searchWagon = ManageWagonController.searchWagons(wagonId);
            wagon.setWagonId(wagonId);
            wagon.setClassType(searchWagon.getClassType());
            wagon.setSheetQuantity(searchWagon.getSheetQuantity());
            String classType = null;
            String status = "Unbooked";
            if (btnFist.isSelected()) {
                classType = "First";
            }
            if (btnSecond.isSelected()) {
                classType = "Second";
            }
            if (btnThird.isSelected()) {
                classType = "Third";
            }
            if (btnObservation.isSelected()) {
                classType = "Observation";
            }
            SheetDto dto = new SheetDto();
            dto.setWagonDto(wagon);
            dto.setSheetType(classType);
            dto.setStatus(status);
            boolean isAdded = ManageSheetController.saveSheet(dto);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Added Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageSheets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSecondActionPerformed

    private void btnThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThirdActionPerformed

    private void tblSheetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSheetMouseClicked
        //selectPrice = (boolean) tblPrices.getValueAt(tblPrices.getSelectedRow(), 0);
        sheetId = (int) tblSheet.getValueAt(tblSheet.getSelectedRow(), 1);
        String wagonId = (String) tblSheet.getValueAt(tblSheet.getSelectedRow(), 2);
        String classType = (String) tblSheet.getValueAt(tblSheet.getSelectedRow(), 3);
        status = (String) tblSheet.getValueAt(tblSheet.getSelectedRow(), 4);
        txtWagonId.setText(wagonId);
        if (classType.equals("First")) {
            btnFist.setSelected(true);
        }

        if (classType.equals("Second")) {
            btnSecond.setSelected(true);
        }
        if (classType.equals("Third")) {
            btnThird.setSelected(true);
        }
        if (classType.equals("Observation")) {
            btnObservation.setSelected(true);
        }

    }//GEN-LAST:event_tblSheetMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String wagonId = txtWagonId.getText();
            WagonDto wagon = new WagonDto();
            WagonDto searchWagon = ManageWagonController.searchWagons(wagonId);
            wagon.setWagonId(wagonId);
            wagon.setClassType(searchWagon.getClassType());
            wagon.setSheetQuantity(searchWagon.getSheetQuantity());
            String classType = null;
            if (btnFist.isSelected()) {
                classType = "First";
            }
            if (btnSecond.isSelected()) {
                classType = "Second";
            }
            if (btnThird.isSelected()) {
                classType = "Third";
            }
            if (btnObservation.isSelected()) {
                classType = "Observation";
            }
            SheetDto dto = new SheetDto();
            dto.setWagonDto(wagon);
            dto.setSheetType(classType);
            dto.setStatus(status);
            dto.setSheetID(sheetId);
            boolean isUpdated = ManageSheetController.updateSheet(dto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Updated Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Updated Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageSheets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnFist;
    private javax.swing.JRadioButton btnObservation;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnSecond;
    private javax.swing.JRadioButton btnThird;
    private javax.swing.ButtonGroup cmbGenderGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlManageUser;
    private javax.swing.JTable tblSheet;
    private javax.swing.JTextField txtWagonId;
    // End of variables declaration//GEN-END:variables

    private void getAllSheets() {
        try {
            List<SheetDto> sheetDto = ManageSheetController.getAllSheets();
            dtm.setRowCount(0);

            if (sheetDto != null) {

                for (SheetDto sheet : sheetDto) {
                    Object[] ob = {false, sheet.getSheetID(), sheet.getWagonDto().getWagonId(), sheet.getSheetType(), sheet.getStatus()};
                    dtm.addRow(ob);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageTrain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @Override
    public void updateObservers() throws Exception {
        getAllSheets();
    }

}
