/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.rtrsc.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.rtrsc.controller.ManageRouteController;
import lk.ijse.rtrsc.controller.ManageTrainController;
import lk.ijse.rtrsc.controller.ManageWagonController;
import lk.ijse.rtrsc.dto.DayDto;
import lk.ijse.rtrsc.dto.RouteDto;
import lk.ijse.rtrsc.dto.ViewWagonDto;
import lk.ijse.rtrsc.dto.WagonDto;

/**
 *
 * @author Gnanod-PC
 */
public class RouteSettingss extends javax.swing.JDialog {

    /**
     * Creates new form WagonSettings
     */
    private DefaultTableModel dtmRoute;
    private String dateId;
    public RouteSettingss(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        dtmRoute = (DefaultTableModel) tblRoute.getModel();
        getRouteDetails();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoute = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDayId = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        chkThursday = new javax.swing.JCheckBox();
        chkSunday = new javax.swing.JCheckBox();
        chkMonday = new javax.swing.JCheckBox();
        chkTuesday = new javax.swing.JCheckBox();
        chkWednesday = new javax.swing.JCheckBox();
        chkHolydays = new javax.swing.JCheckBox();
        chkSaturday = new javax.swing.JCheckBox();
        chkFriday = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        txtUserId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserIdKeyPressed(evt);
            }
        });
        getContentPane().add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 400, 30));

        jButton1.setText("Search");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 90, 30));

        tblRoute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "RouteId", "DayId", "RouteName", "DepatureTime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRouteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRoute);
        if (tblRoute.getColumnModel().getColumnCount() > 0) {
            tblRoute.getColumnModel().getColumn(0).setMinWidth(50);
            tblRoute.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 180));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 120, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 157, 175));
        jLabel12.setText("Day Id");
        jLabel12.setToolTipText("");
        jLabel12.setOpaque(true);
        jLabel12.setRequestFocusEnabled(false);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 30));
        getContentPane().add(txtDayId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 300, 30));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, 40));

        chkThursday.setBackground(new java.awt.Color(255, 255, 255));
        chkThursday.setText("Thursday");
        getContentPane().add(chkThursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 90, -1));

        chkSunday.setBackground(new java.awt.Color(255, 255, 255));
        chkSunday.setText("Sunday");
        chkSunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSundayActionPerformed(evt);
            }
        });
        getContentPane().add(chkSunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        chkMonday.setBackground(new java.awt.Color(255, 255, 255));
        chkMonday.setText("Monday");
        chkMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMondayActionPerformed(evt);
            }
        });
        getContentPane().add(chkMonday, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 80, -1));

        chkTuesday.setBackground(new java.awt.Color(255, 255, 255));
        chkTuesday.setText("Tuesday");
        chkTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTuesdayActionPerformed(evt);
            }
        });
        getContentPane().add(chkTuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 100, -1));

        chkWednesday.setBackground(new java.awt.Color(255, 255, 255));
        chkWednesday.setText("Wednesday");
        chkWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWednesdayActionPerformed(evt);
            }
        });
        getContentPane().add(chkWednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 110, -1));

        chkHolydays.setBackground(new java.awt.Color(255, 255, 255));
        chkHolydays.setText("HoliDays");
        chkHolydays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHolydaysActionPerformed(evt);
            }
        });
        getContentPane().add(chkHolydays, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 110, -1));

        chkSaturday.setBackground(new java.awt.Color(255, 255, 255));
        chkSaturday.setText("Saturday");
        chkSaturday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSaturdayActionPerformed(evt);
            }
        });
        getContentPane().add(chkSaturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 110, -1));

        chkFriday.setBackground(new java.awt.Color(255, 255, 255));
        chkFriday.setText("Friday");
        getContentPane().add(chkFriday, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(27, 157, 175));
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Travelling Dates", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(27, 157, 175))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 480, 110));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed

    }//GEN-LAST:event_txtUserIdActionPerformed

    private void txtUserIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIdKeyPressed
       
    }//GEN-LAST:event_txtUserIdKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       try {
            String routeId = tblRoute.getValueAt(tblRoute.getSelectedRow(), 1).toString();
        
        
            boolean isDeleted = ManageRouteController.deleteRoute(routeId);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Deleted SuccessFully");
                
            } else {
                JOptionPane.showMessageDialog(this, "Deleted Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(RouteSettingss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//        try {
//            String wagonId = txtWagonId.getText();
//            String trainId = txtTrainId.getText();
//            String sheetQty = txtSheetQty.getText();
//           
//            
//            String classType = tblWagon.getValueAt(tblWagon.getSelectedRow(), 4).toString();
//            System.out.println("classType"+classType);
//            if(classType.equals("FirstClass")){
//                btnFirst.isSelected();
//            }
//            if(classType.equals("SecondClass")){
//                btnSecond.isSelected();
//            }
//            if(classType.equals("ThirdClass")){
//                btnThird.isSelected();
//            }
//            if(classType.equals("ObservationSaloon")){
//                btnObservation.isSelected();
//            }
//            
//            WagonDto wagon = new WagonDto();
//            wagon.setClassType(classType);
//            wagon.setSheetQuantity(Integer.parseInt(sheetQty));
//            wagon.setWagonId(wagonId);
//            boolean isUpdated = ManageWagonController.updateWagon(wagon);
//            if(isUpdated){
//                JOptionPane.showMessageDialog(this,"Updated Successfully");
//            }else{
//                JOptionPane.showMessageDialog(this,"Updated Fail");
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(RouteSettingss.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRouteMouseClicked
          dateId = tblRoute.getValueAt(tblRoute.getSelectedRow(), 2).toString();
          searchRouteDay(dateId);
        
//        String wagonId = tblWagon.getValueAt(tblWagon.getSelectedRow(), 1).toString();
//        String trainId = tblWagon.getValueAt(tblWagon.getSelectedRow(), 2).toString();
//        String sheetQty = tblWagon.getValueAt(tblWagon.getSelectedRow(), 4).toString();
//        String classType = tblWagon.getValueAt(tblWagon.getSelectedRow(), 3).toString();
//       
//        if(classType.equals("FirstClass")){
//            btnFirst.setSelected(true);
//        }
//        if(classType.equals("SecondClass")){
//            btnSecond.setSelected(true);
//        }
//        if(classType.equals("ThirdClass")){
//            btnThird.setSelected(true);
//        }
//        if(classType.equals("ObservationSaloon")){
//            btnObservation.setSelected(true);
//        }
//        txtWagonId.setText(wagonId);
//        txtTrainId.setText(trainId);
//        txtSheetQty.setText(sheetQty);
       
    }//GEN-LAST:event_tblRouteMouseClicked

    private void chkSundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSundayActionPerformed

    private void chkMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMondayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMondayActionPerformed

    private void chkTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTuesdayActionPerformed

    private void chkWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWednesdayActionPerformed

    private void chkHolydaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHolydaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHolydaysActionPerformed

    private void chkSaturdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSaturdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSaturdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RouteSettingss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RouteSettingss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RouteSettingss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RouteSettingss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RouteSettingss dialog = new RouteSettingss(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkFriday;
    private javax.swing.JCheckBox chkHolydays;
    private javax.swing.JCheckBox chkMonday;
    private javax.swing.JCheckBox chkSaturday;
    private javax.swing.JCheckBox chkSunday;
    private javax.swing.JCheckBox chkThursday;
    private javax.swing.JCheckBox chkTuesday;
    private javax.swing.JCheckBox chkWednesday;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRoute;
    private javax.swing.JTextField txtDayId;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables

    private void getRouteDetails() {
        try {
            List<RouteDto> list = ManageRouteController.getAllRoutes();
            dtmRoute.setRowCount(0);
            System.out.println("rrrrrr"+list);
            if(list!=null){
                for (RouteDto routeDto : list) {
                    Object []ob ={false,routeDto.getRouteId(),routeDto.getDayDto().getDateId(),routeDto.getRouteName(),routeDto.getDepatureTime()};
                    dtmRoute.addRow(ob);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(RouteSettingss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchRouteDay(String dateId) {
        try {
            txtDayId.setText(dateId);
            DayDto dto = ManageRouteController.searchDays(dateId);
            boolean friday = dto.isFriday();
            boolean holyday = dto.isHoliday();
            boolean monday = dto.isMonday();
            boolean saturday = dto.isSaturday();
            boolean tuesday = dto.isTuesday();
            boolean wednesday = dto.isWednesday();
            boolean sunday = dto.isSunday();
            boolean thursday = dto.isThursday();
            
            if(friday==true){
                chkFriday.setSelected(true);
            }
            if(sunday==true){
                chkSunday.setSelected(true);
            }
            if(saturday==true){
                chkSaturday.setSelected(true);
            }
            if(monday==true){
                chkMonday.setSelected(true);
            }
            if(friday==true){
                chkFriday.setSelected(true);
            }
            if(tuesday==true){
                chkTuesday.setSelected(true);
            }
            if(wednesday==true){
                chkWednesday.setSelected(true);
            }
            if(holyday==true){
                chkHolydays.setSelected(true);
            }
             if(thursday==true){
                chkThursday.setSelected(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(RouteSettingss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
